vich_uploader:
    db_driver: orm

    mappings:
        serial_images:
            uri_prefix:         '%app.path.serial_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.serial_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        season_images:
            uri_prefix:         '%app.path.season_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.season_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        episode_images:
            uri_prefix:         '%app.path.episode_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.episode_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
