vich_uploader:
    db_driver: orm

    mappings:
        serial_images:
            uri_prefix:         '%app.path.serial_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.serial_images%'
